name: Periodic Script Runner

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Script
        run: streamlit run trythisapp.py  # Replace with your script name
